services:
  - type: worker
    name: weather-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python weatherapi_bot.py
    envVars:
      - key: WEATHER_API_KEY
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
